{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "This notebook is an experimentation with building user profiles using Django (following [this](https://dev.to/earthcomfy/creating-a-django-registration-login-app-part-i-1di5) tutorial)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Installations"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "NOTE: If adding a new column to the database, first delete 'db.sqlite3', then rerun this notebook"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: Django in /opt/anaconda3/lib/python3.8/site-packages (3.2.6)\r\n",
      "Requirement already satisfied: sqlparse>=0.2.2 in /opt/anaconda3/lib/python3.8/site-packages (from Django) (0.4.2)\r\n",
      "Requirement already satisfied: asgiref<4,>=3.3.2 in /opt/anaconda3/lib/python3.8/site-packages (from Django) (3.5.2)\r\n",
      "Requirement already satisfied: pytz in /opt/anaconda3/lib/python3.8/site-packages (from Django) (2020.1)\r\n"
     ]
    }
   ],
   "source": [
    "!pip install Django\n",
    "import django"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: Django==3.2.6 in /opt/anaconda3/lib/python3.8/site-packages (from -r user-profile-system/requirements.txt (line 1)) (3.2.6)\n",
      "Requirement already satisfied: Pillow==8.3.1 in /opt/anaconda3/lib/python3.8/site-packages (from -r user-profile-system/requirements.txt (line 2)) (8.3.1)\n",
      "Requirement already satisfied: python-dotenv==0.19.0 in /opt/anaconda3/lib/python3.8/site-packages (from -r user-profile-system/requirements.txt (line 3)) (0.19.0)\n",
      "Requirement already satisfied: social-auth-app-django==5.0.0 in /opt/anaconda3/lib/python3.8/site-packages (from -r user-profile-system/requirements.txt (line 4)) (5.0.0)\n",
      "Requirement already satisfied: pytz in /opt/anaconda3/lib/python3.8/site-packages (from Django==3.2.6->-r user-profile-system/requirements.txt (line 1)) (2020.1)\n",
      "Requirement already satisfied: sqlparse>=0.2.2 in /opt/anaconda3/lib/python3.8/site-packages (from Django==3.2.6->-r user-profile-system/requirements.txt (line 1)) (0.4.2)\n",
      "Requirement already satisfied: asgiref<4,>=3.3.2 in /opt/anaconda3/lib/python3.8/site-packages (from Django==3.2.6->-r user-profile-system/requirements.txt (line 1)) (3.5.2)\n",
      "Requirement already satisfied: social-auth-core>=4.1.0 in /opt/anaconda3/lib/python3.8/site-packages (from social-auth-app-django==5.0.0->-r user-profile-system/requirements.txt (line 4)) (4.3.0)\n",
      "Requirement already satisfied: defusedxml>=0.5.0rc1 in /opt/anaconda3/lib/python3.8/site-packages (from social-auth-core>=4.1.0->social-auth-app-django==5.0.0->-r user-profile-system/requirements.txt (line 4)) (0.6.0)\n",
      "Requirement already satisfied: PyJWT>=2.0.0 in /opt/anaconda3/lib/python3.8/site-packages (from social-auth-core>=4.1.0->social-auth-app-django==5.0.0->-r user-profile-system/requirements.txt (line 4)) (2.4.0)\n",
      "Requirement already satisfied: cryptography>=1.4 in /opt/anaconda3/lib/python3.8/site-packages (from social-auth-core>=4.1.0->social-auth-app-django==5.0.0->-r user-profile-system/requirements.txt (line 4)) (3.1.1)\n",
      "Requirement already satisfied: requests>=2.9.1 in /opt/anaconda3/lib/python3.8/site-packages (from social-auth-core>=4.1.0->social-auth-app-django==5.0.0->-r user-profile-system/requirements.txt (line 4)) (2.24.0)\n",
      "Requirement already satisfied: oauthlib>=1.0.3 in /opt/anaconda3/lib/python3.8/site-packages (from social-auth-core>=4.1.0->social-auth-app-django==5.0.0->-r user-profile-system/requirements.txt (line 4)) (3.2.0)\n",
      "Requirement already satisfied: python3-openid>=3.0.10 in /opt/anaconda3/lib/python3.8/site-packages (from social-auth-core>=4.1.0->social-auth-app-django==5.0.0->-r user-profile-system/requirements.txt (line 4)) (3.2.0)\n",
      "Requirement already satisfied: requests-oauthlib>=0.6.1 in /opt/anaconda3/lib/python3.8/site-packages (from social-auth-core>=4.1.0->social-auth-app-django==5.0.0->-r user-profile-system/requirements.txt (line 4)) (1.3.1)\n",
      "Requirement already satisfied: six>=1.4.1 in /opt/anaconda3/lib/python3.8/site-packages (from cryptography>=1.4->social-auth-core>=4.1.0->social-auth-app-django==5.0.0->-r user-profile-system/requirements.txt (line 4)) (1.15.0)\n",
      "Requirement already satisfied: cffi!=1.11.3,>=1.8 in /opt/anaconda3/lib/python3.8/site-packages (from cryptography>=1.4->social-auth-core>=4.1.0->social-auth-app-django==5.0.0->-r user-profile-system/requirements.txt (line 4)) (1.14.3)\n",
      "Requirement already satisfied: chardet<4,>=3.0.2 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.9.1->social-auth-core>=4.1.0->social-auth-app-django==5.0.0->-r user-profile-system/requirements.txt (line 4)) (3.0.4)\n",
      "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.9.1->social-auth-core>=4.1.0->social-auth-app-django==5.0.0->-r user-profile-system/requirements.txt (line 4)) (1.22)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.9.1->social-auth-core>=4.1.0->social-auth-app-django==5.0.0->-r user-profile-system/requirements.txt (line 4)) (2020.6.20)\n",
      "Requirement already satisfied: idna<3,>=2.5 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.9.1->social-auth-core>=4.1.0->social-auth-app-django==5.0.0->-r user-profile-system/requirements.txt (line 4)) (2.10)\n",
      "Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.8/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=1.4->social-auth-core>=4.1.0->social-auth-app-django==5.0.0->-r user-profile-system/requirements.txt (line 4)) (2.20)\n"
     ]
    }
   ],
   "source": [
    "!pip install -r user-profile-system/requirements.txt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[36;1mMigrations for 'users':\u001b[0m\r\n",
      "  \u001b[1muser-profile-system/users/migrations/0006_auto_20220623_1946.py\u001b[0m\r\n",
      "    - Add field year to profile\r\n",
      "    - Alter field institution on profile\r\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!python user-profile-system/manage.py makemigrations"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[36;1mOperations to perform:\u001b[0m\n",
      "\u001b[1m  Apply all migrations: \u001b[0madmin, auth, contenttypes, sessions, social_django, users\n",
      "\u001b[36;1mRunning migrations:\u001b[0m\n",
      "  Applying contenttypes.0001_initial...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0001_initial...\u001b[32;1m OK\u001b[0m\n",
      "  Applying admin.0001_initial...\u001b[32;1m OK\u001b[0m\n",
      "  Applying admin.0002_logentry_remove_auto_add...\u001b[32;1m OK\u001b[0m\n",
      "  Applying admin.0003_logentry_add_action_flag_choices...\u001b[32;1m OK\u001b[0m\n",
      "  Applying contenttypes.0002_remove_content_type_name...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0002_alter_permission_name_max_length...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0003_alter_user_email_max_length...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0004_alter_user_username_opts...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0005_alter_user_last_login_null...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0006_require_contenttypes_0002...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0007_alter_validators_add_error_messages...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0008_alter_user_username_max_length...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0009_alter_user_last_name_max_length...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0010_alter_group_name_max_length...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0011_update_proxy_permissions...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0012_alter_user_first_name_max_length...\u001b[32;1m OK\u001b[0m\n",
      "  Applying sessions.0001_initial...\u001b[32;1m OK\u001b[0m\n",
      "  Applying social_django.0001_initial...\u001b[32;1m OK\u001b[0m\n",
      "  Applying social_django.0002_add_related_name...\u001b[32;1m OK\u001b[0m\n",
      "  Applying social_django.0003_alter_email_max_length...\u001b[32;1m OK\u001b[0m\n",
      "  Applying social_django.0004_auto_20160423_0400...\u001b[32;1m OK\u001b[0m\n",
      "  Applying social_django.0005_auto_20160727_2333...\u001b[32;1m OK\u001b[0m\n",
      "  Applying social_django.0006_partial...\u001b[32;1m OK\u001b[0m\n",
      "  Applying social_django.0007_code_timestamp...\u001b[32;1m OK\u001b[0m\n",
      "  Applying social_django.0008_partial_timestamp...\u001b[32;1m OK\u001b[0m\n",
      "  Applying social_django.0009_auto_20191118_0520...\u001b[32;1m OK\u001b[0m\n",
      "  Applying social_django.0010_uid_db_index...\u001b[32;1m OK\u001b[0m\n",
      "  Applying users.0001_initial...\u001b[32;1m OK\u001b[0m\n",
      "  Applying users.0002_alter_profile_avatar...\u001b[32;1m OK\u001b[0m\n",
      "  Applying users.0003_alter_profile_avatar...\u001b[32;1m OK\u001b[0m\n",
      "  Applying users.0004_profile_bio...\u001b[32;1m OK\u001b[0m\n",
      "  Applying users.0005_profile_institution...\u001b[32;1m OK\u001b[0m\n",
      "  Applying users.0006_auto_20220623_1946...\u001b[32;1m OK\u001b[0m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!python user-profile-system/manage.py migrate"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Watching for file changes with StatReloader\n",
      "Performing system checks...\n",
      "\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/utils/autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/core/management/commands/runserver.py\", line 118, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/core/management/base.py\", line 419, in check\n",
      "    all_issues = checks.run_checks(\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/core/checks/registry.py\", line 76, in run_checks\n",
      "    new_errors = check(app_configs=app_configs, databases=databases)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/core/checks/urls.py\", line 13, in check_url_config\n",
      "    return check_resolver(resolver)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/core/checks/urls.py\", line 23, in check_resolver\n",
      "    return check_method()\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/urls/resolvers.py\", line 412, in check\n",
      "    for pattern in self.url_patterns:\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/utils/functional.py\", line 48, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/urls/resolvers.py\", line 598, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/utils/functional.py\", line 48, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/urls/resolvers.py\", line 591, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "  File \"/opt/anaconda3/lib/python3.8/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/mallard/Documents/GitHub/Summer-2022/user-profile-system/user_management/urls.py\", line 17, in <module>\n",
      "    path('', include('users.urls')),\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/urls/conf.py\", line 34, in include\n",
      "    urlconf_module = import_module(urlconf_module)\n",
      "  File \"/opt/anaconda3/lib/python3.8/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/mallard/Documents/GitHub/Summer-2022/user-profile-system/users/urls.py\", line 9, in <module>\n",
      "    path('exercises/', exercises, name='users-exercises'),\n",
      "NameError: name 'exercises' is not defined\n",
      "/Users/mallard/Documents/GitHub/Summer-2022/user-profile-system/users/urls.py changed, reloading.\n",
      "\u001b[0mWatching for file changes with StatReloader\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "June 24, 2022 - 17:13:10\n",
      "Django version 3.2.6, using settings 'user_management.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "[24/Jun/2022 17:13:11] \u001b[m\"GET / HTTP/1.1\" 200 3006\u001b[0m\n",
      "[24/Jun/2022 17:13:13] \u001b[m\"GET /exercises/ HTTP/1.1\" 200 2807\u001b[0m\n",
      "[24/Jun/2022 17:13:20] \u001b[m\"GET /progress/ HTTP/1.1\" 200 2830\u001b[0m\n",
      "[24/Jun/2022 17:13:24] \u001b[m\"GET /profile/ HTTP/1.1\" 200 5054\u001b[0m\n",
      "[24/Jun/2022 17:13:31] \u001b[m\"GET /exercises/ HTTP/1.1\" 200 2807\u001b[0m\n",
      "[24/Jun/2022 17:13:33] \u001b[m\"GET / HTTP/1.1\" 200 3006\u001b[0m\n",
      "/Users/mallard/Documents/GitHub/Summer-2022/user-profile-system/users/views.py changed, reloading.\n",
      "\u001b[0mWatching for file changes with StatReloader\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "June 24, 2022 - 17:36:56\n",
      "Django version 3.2.6, using settings 'user_management.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "/Users/mallard/Documents/GitHub/Summer-2022/user-profile-system/users/views.py changed, reloading.\n",
      "\u001b[0mWatching for file changes with StatReloader\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "June 24, 2022 - 17:38:55\n",
      "Django version 3.2.6, using settings 'user_management.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "[24/Jun/2022 17:39:12] \u001b[m\"GET / HTTP/1.1\" 200 3006\u001b[0m\n",
      "Internal Server Error: /exercises/\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py\", line 47, in inner\n",
      "    response = get_response(request)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py\", line 181, in _get_response\n",
      "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/contrib/auth/decorators.py\", line 21, in _wrapped_view\n",
      "    return view_func(request, *args, **kwargs)\n",
      "  File \"/Users/mallard/Documents/GitHub/Summer-2022/user-profile-system/users/views.py\", line 112, in exercises\n",
      "    demo.launch()\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/gradio/blocks.py\", line 742, in launch\n",
      "    utils.synchronize_async(self.create_limiter, max_threads)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/gradio/utils.py\", line 316, in synchronize_async\n",
      "    event_loop = asyncio.get_event_loop()\n",
      "  File \"/opt/anaconda3/lib/python3.8/asyncio/events.py\", line 639, in get_event_loop\n",
      "    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "RuntimeError: There is no current event loop in thread 'Thread-1'.\n",
      "[24/Jun/2022 17:39:22] \u001b[35;1m\"GET /exercises/ HTTP/1.1\" 500 80848\u001b[0m\n",
      "/Users/mallard/Documents/GitHub/Summer-2022/user-profile-system/users/views.py changed, reloading.\n",
      "\u001b[0mWatching for file changes with StatReloader\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "June 24, 2022 - 17:41:22\n",
      "Django version 3.2.6, using settings 'user_management.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "Internal Server Error: /exercises/\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py\", line 47, in inner\n",
      "    response = get_response(request)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py\", line 181, in _get_response\n",
      "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/contrib/auth/decorators.py\", line 21, in _wrapped_view\n",
      "    return view_func(request, *args, **kwargs)\n",
      "  File \"/Users/mallard/Documents/GitHub/Summer-2022/user-profile-system/users/views.py\", line 114, in exercises\n",
      "    return render(request, 'users/exercises.html', {\"demo\": demo})\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/shortcuts.py\", line 19, in render\n",
      "    content = loader.render_to_string(template_name, context, request, using=using)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/loader.py\", line 62, in render_to_string\n",
      "    return template.render(context, request)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/backends/django.py\", line 61, in render\n",
      "    return self.template.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 170, in render\n",
      "    return self._render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 162, in _render\n",
      "    return self.nodelist.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 938, in render\n",
      "    bit = node.render_annotated(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 905, in render_annotated\n",
      "    return self.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py\", line 150, in render\n",
      "    return compiled_parent._render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 162, in _render\n",
      "    return self.nodelist.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 938, in render\n",
      "    bit = node.render_annotated(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 905, in render_annotated\n",
      "    return self.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py\", line 62, in render\n",
      "    result = block.nodelist.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 938, in render\n",
      "    bit = node.render_annotated(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 905, in render_annotated\n",
      "    return self.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 988, in render\n",
      "    output = self.filter_expression.resolve(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 671, in resolve\n",
      "    obj = self.var.resolve(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 796, in resolve\n",
      "    value = self._resolve_lookup(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 858, in _resolve_lookup\n",
      "    current = current()\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/gradio/interface.py\", line 636, in __call__\n",
      "    output = self.process(params)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/gradio/interface.py\", line 710, in process\n",
      "    processed_input = [\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/gradio/interface.py\", line 711, in <listcomp>\n",
      "    input_component.preprocess(raw_input[i])\n",
      "IndexError: tuple index out of range\n",
      "[24/Jun/2022 17:41:28] \u001b[35;1m\"GET /exercises/ HTTP/1.1\" 500 164905\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[24/Jun/2022 17:41:41] \u001b[m\"GET / HTTP/1.1\" 200 3006\u001b[0m\n",
      "Internal Server Error: /exercises/\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py\", line 47, in inner\n",
      "    response = get_response(request)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py\", line 181, in _get_response\n",
      "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/contrib/auth/decorators.py\", line 21, in _wrapped_view\n",
      "    return view_func(request, *args, **kwargs)\n",
      "  File \"/Users/mallard/Documents/GitHub/Summer-2022/user-profile-system/users/views.py\", line 114, in exercises\n",
      "    return render(request, 'users/exercises.html', {\"demo\": demo})\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/shortcuts.py\", line 19, in render\n",
      "    content = loader.render_to_string(template_name, context, request, using=using)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/loader.py\", line 62, in render_to_string\n",
      "    return template.render(context, request)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/backends/django.py\", line 61, in render\n",
      "    return self.template.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 170, in render\n",
      "    return self._render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 162, in _render\n",
      "    return self.nodelist.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 938, in render\n",
      "    bit = node.render_annotated(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 905, in render_annotated\n",
      "    return self.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py\", line 150, in render\n",
      "    return compiled_parent._render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 162, in _render\n",
      "    return self.nodelist.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 938, in render\n",
      "    bit = node.render_annotated(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 905, in render_annotated\n",
      "    return self.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py\", line 62, in render\n",
      "    result = block.nodelist.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 938, in render\n",
      "    bit = node.render_annotated(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 905, in render_annotated\n",
      "    return self.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 988, in render\n",
      "    output = self.filter_expression.resolve(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 671, in resolve\n",
      "    obj = self.var.resolve(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 796, in resolve\n",
      "    value = self._resolve_lookup(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 858, in _resolve_lookup\n",
      "    current = current()\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/gradio/interface.py\", line 636, in __call__\n",
      "    output = self.process(params)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/gradio/interface.py\", line 710, in process\n",
      "    processed_input = [\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/gradio/interface.py\", line 711, in <listcomp>\n",
      "    input_component.preprocess(raw_input[i])\n",
      "IndexError: tuple index out of range\n",
      "[24/Jun/2022 17:41:44] \u001b[35;1m\"GET /exercises/ HTTP/1.1\" 500 164919\u001b[0m\n",
      "[24/Jun/2022 17:41:47] \u001b[m\"GET /progress/ HTTP/1.1\" 200 2830\u001b[0m\n",
      "[24/Jun/2022 17:41:48] \u001b[m\"GET /profile/ HTTP/1.1\" 200 5054\u001b[0m\n",
      "Internal Server Error: /exercises/\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py\", line 47, in inner\n",
      "    response = get_response(request)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py\", line 181, in _get_response\n",
      "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/contrib/auth/decorators.py\", line 21, in _wrapped_view\n",
      "    return view_func(request, *args, **kwargs)\n",
      "  File \"/Users/mallard/Documents/GitHub/Summer-2022/user-profile-system/users/views.py\", line 114, in exercises\n",
      "    return render(request, 'users/exercises.html', {\"demo\": demo})\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/shortcuts.py\", line 19, in render\n",
      "    content = loader.render_to_string(template_name, context, request, using=using)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/loader.py\", line 62, in render_to_string\n",
      "    return template.render(context, request)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/backends/django.py\", line 61, in render\n",
      "    return self.template.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 170, in render\n",
      "    return self._render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 162, in _render\n",
      "    return self.nodelist.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 938, in render\n",
      "    bit = node.render_annotated(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 905, in render_annotated\n",
      "    return self.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py\", line 150, in render\n",
      "    return compiled_parent._render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 162, in _render\n",
      "    return self.nodelist.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 938, in render\n",
      "    bit = node.render_annotated(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 905, in render_annotated\n",
      "    return self.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py\", line 62, in render\n",
      "    result = block.nodelist.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 938, in render\n",
      "    bit = node.render_annotated(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 905, in render_annotated\n",
      "    return self.render(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 988, in render\n",
      "    output = self.filter_expression.resolve(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 671, in resolve\n",
      "    obj = self.var.resolve(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 796, in resolve\n",
      "    value = self._resolve_lookup(context)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py\", line 858, in _resolve_lookup\n",
      "    current = current()\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/gradio/interface.py\", line 636, in __call__\n",
      "    output = self.process(params)\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/gradio/interface.py\", line 710, in process\n",
      "    processed_input = [\n",
      "  File \"/opt/anaconda3/lib/python3.8/site-packages/gradio/interface.py\", line 711, in <listcomp>\n",
      "    input_component.preprocess(raw_input[i])\n",
      "IndexError: tuple index out of range\n",
      "[24/Jun/2022 17:41:51] \u001b[35;1m\"GET /exercises/ HTTP/1.1\" 500 164927\u001b[0m\n",
      "/Users/mallard/Documents/GitHub/Summer-2022/user-profile-system/users/views.py changed, reloading.\n",
      "\u001b[0mWatching for file changes with StatReloader\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "June 24, 2022 - 17:56:39\n",
      "Django version 3.2.6, using settings 'user_management.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "[24/Jun/2022 17:56:44] \u001b[m\"GET /exercises/ HTTP/1.1\" 200 2820\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[24/Jun/2022 17:57:06] \u001b[m\"GET /exercises/ HTTP/1.1\" 200 3462\u001b[0m\n",
      "[24/Jun/2022 17:57:46] \u001b[m\"GET /exercises/ HTTP/1.1\" 200 3122\u001b[0m\n",
      "[24/Jun/2022 18:03:10] \u001b[m\"GET /exercises/ HTTP/1.1\" 200 3108\u001b[0m\n",
      "[24/Jun/2022 18:07:53] \u001b[m\"GET /exercises/ HTTP/1.1\" 200 3108\u001b[0m\n",
      "[24/Jun/2022 18:07:55] \u001b[m\"GET /progress/ HTTP/1.1\" 200 2830\u001b[0m\n",
      "[24/Jun/2022 18:07:57] \u001b[m\"GET /profile/ HTTP/1.1\" 200 5054\u001b[0m\n",
      "[24/Jun/2022 18:07:58] \u001b[m\"GET /exercises/ HTTP/1.1\" 200 3108\u001b[0m\n",
      "[24/Jun/2022 18:07:59] \u001b[m\"GET / HTTP/1.1\" 200 3006\u001b[0m\n",
      "^C\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!python user-profile-system/manage.py runserver"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Potentially Useful Links"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "This documentation on [django authentication](https://docs.djangoproject.com/en/4.0/topics/auth/default/) may prove useful if we decide to assign different roles (i.e. student and instructor)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "[This](https://stackoverflow.com/questions/41990794/django-executing-python-code-in-html) page describes how to execute python code in html with Django"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "[Gradio](https://gradio.app/using_hugging_face_integrations/) allows its apps to be embedded into html"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
